---
- hosts: aliyun_allserver
  remote_user: root
  gather_facts: no
  tasks:
    - name: add user and group
      user: name="{{ item.name }}" password="{{ item.chpass | password_hash('sha512') }}" 
      with_items:
        - {name: "trio", chpass: "TrioOnline"}
